- job_name: 'ec2'
  metrics_path: /metrics
  static_configs:
    - targets: 
      - 13.58.122.139:9100
      - 13.58.122.139:80
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - http://13.58.122.139
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: 10.100.1.199:9115